# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'rubocop', '>= 1.89'

gem 'httparty', '>= 0.24.2'

gem 'pry', '>= 0.16.0'

gem 'faker', '>= 3.8'

gem 'colorize', '>= 1.1'

gem 'json', '>= 2.21.2'

gem 'csv', '>= 3.3.6'

gem 'rspec', '>= 3.13.2'